module.exports = Object.freeze({
  PLAYER_RADIUS: 20,
  PLAYER_INIT_SIZE: 30,
  PLAYER_MAX_SIZE: 200,
  PLAYER_INIT_SPEED: 300,
  PLAYER_BOOST_COOLDOWN: 0.25,
  PLAYER_BOOST_RATIO: 600,
  PLAYER_BOOST_DURATION: 500,
  PLAYER_LOST_CONTROL_DURATION: 1500,


  SUCK_ADDITION: 1,
  DROP_DECREASE: 5,
  MAX_PART_RATIO:3,
  HIT_DAMAGE: 10,
  BULLET_RADIUS: 10,

  SCORE_SUCK: 5,
  SCORE_PER_SECOND: 1,

  PART_GEN_CD: 400,
  PART_AMOUNT_MAX: 100,

  CANVAS_ENLARGE_SIZE: 120,
  CANVAS_ENLARGE_SPEED: 0.005,

  MAP_SIZE: 3000,
  MSG_TYPES: {
    JOIN_GAME: 'join_game',
    GAME_UPDATE: 'update',
    INPUT: 'input',
    GAME_OVER: 'dead',
    TRIG_BOOST: 'trigger boost',
  },
});
